[package]

name = "yup-oauth2"
version = "3.1.1"
authors = ["Sebastian Thiel <byronimo@gmail.com>", "Lewin Bormann <lbo@spheniscida.de>"]
repository = "https://github.com/dermesser/yup-oauth2"
description = "An oauth2 implementation, providing the 'device', 'service account' and 'installed' authorization flows"
documentation = "https://docs.rs/yup-oauth2/"
keywords = ["google", "oauth", "v2"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
http = "0.1"
hyper = {version = "0.13.0-alpha.4", features = ["unstable-stream"]}
hyper-rustls = "=0.18.0-alpha.2"
log = "0.4"
rustls = "0.16"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
url = "1"
futures-preview = "=0.3.0-alpha.19"
tokio = "=0.2.0-alpha.6"
futures-util-preview = "=0.3.0-alpha.19"
seahash = "3.0.6"

[dev-dependencies]
mockito = "0.17"
env_logger = "0.6"

[workspace]
members = ["examples/test-installed/", "examples/test-svc-acct/", "examples/test-device/"]
